work_dir: ./work_dir/match/ctrgcn_longtail
confidence_dir: ./work_dir/match/confidence_B

# feeder
feeder: feeders.feeder_B.Feeder
test_feeder_args:
  data_path: ./data/match/test_B_joint.npy
  window_size: 120
  p_interval: [0.95]
  vel: False
  bone: True
  debug: False
  normalization: True
  
# model
model: model.ctrgcn.Model
model_args:
  num_class: 155
  num_point: 17
  num_person: 2
  graph: graph.uav_human.Graph
  graph_args:
    labeling_mode: 'spatial'

# test 
phase: eval_B
device: [0,1,2,3]
test_batch_size: 128
weights: ./work_dir/match/ctrgcn_longtail/runs-best-40-10240.pt


