# feeder
feeder: feeders.feeder_uav.Feeder
train_feeder_args:
  data_path: ./data/match/train_joint.npy
  label_path: ./data/match/train_label.npy
  debug: False
  random_choose: True
  random_shift: False
  random_move: False
  window_size: 52
  normalization: False

test_feeder_args:
  data_path: ./data/match/test_A_joint.npy
  label_path: ./data/match/test_A_label.npy
  debug: False


# model
model: model.ctrgcn.Model
model_args:
  num_class: 155
  num_point: 17
  num_person: 2
  graph: graph.uav_human.Graph
  graph_args:
    labeling_mode: 'spatial'

#optim
weight_decay: 0.0001
base_lr: 0.1
lr_decay_rate: 0.1
step: [50]

# training
device: [0,1,2,3]
batch_size: 16
test_batch_size: 64
num_epoch: 65
nesterov: True
warm_up_epoch: 5
