# command line: main_logit_adjust.py --config ./config/match/train_joint.yaml

base_lr: 0.1
batch_size: 16
cb_loss: false
config: ./config/match/train_joint.yaml
device:
- 0
- 1
- 2
- 3
eval_interval: 5
feeder: feeders.feeder_uav.Feeder
ignore_weights: []
log_interval: 100
lr_decay_rate: 0.1
model: model.ctrgcn.Model
model_args:
  graph: graph.uav_human.Graph
  graph_args:
    labeling_mode: spatial
  num_class: 155
  num_person: 2
  num_point: 17
model_saved_name: ''
nesterov: true
num_epoch: 65
num_worker: 32
optimizer: SGD
phase: train
print_log: true
save_epoch: 30
save_interval: 1
save_score: false
seed: 1
show_topk:
- 1
- 5
start_epoch: 0
step:
- 50
test_batch_size: 64
test_feeder_args:
  data_path: ./data/match/test_joint.npy
  debug: false
  label_path: ./data/match/test_label.npy
train_feeder_args:
  data_path: ./data/match/train_joint.npy
  debug: false
  label_path: ./data/match/train_label.npy
  normalization: false
  random_choose: true
  random_move: false
  random_shift: false
  window_size: 52
warm_up_epoch: 5
weight_decay: 0.0001
weights: null
work_dir: ./work_dir/temp
